# Use postgres/example (user/password) credentials
# run via:
# docker-compose -f stack.yml up
version: '3.1'

services:

  db:
    image: postgres:10.10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
