# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:h2:file:~/IdeaProjects/github.com/spiral-learning/kid-bank/txns;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
#spring.datasource.driver-class-name=org.h2.Driver

# For the Phone Number Authorizer
# Must be in E.164 format
sms.phone.number:
      parent: +16505551212
      kid: +14155554321

# Feature flag for notifying on balance change
feature:
  notify.balance.change: false

# Turn off caching for Thymeleaf templates
spring:
  thymeleaf:
    cache: false


# Configuration for Google OAuth2

security:
  oauth2:
    client:
      clientId: ${com.google.clientId}
      clientSecret: ${com.google.clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false
