# Feature flag for notifying on balance change
feature:
  notify.balance.change: false

# Turn off caching for Thymeleaf templates
spring:
  thymeleaf:
    cache: false

  # Hibernate ddl auto (create, create-drop, validate, update)
  # Use validate just to make sure everything's OK, otherwise Flyway takes care of schemas
  jpa:
    hibernate:
      ddl-auto: validate


# Configuration for Google OAuth2

security:
  oauth2:
    client:
      clientId: ${com.google.clientId}
      clientSecret: ${com.google.clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false
